name: Test workflow dispatch

on:
  workflow_dispatch:
    inputs:
      openshift_cluster:
        description: What cluster
        required: true
        type: choice
        options:
          - test
          - at
          - prod

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Doing work"
          sleep 2
          echo "Done"
  
  deploy_at:
    uses: ./.github/workflows/test-workflow-call.yaml
    needs: dummy
    with:
      cluster: ${{ inputs.openshift_cluster }}
