name: "Test timing of processes"

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  annotate:
    runs-on: ubuntu-latest
    steps:
      - name: Main
        run: |-
          echo "$SECONDS"
          sleep 10
          echo "$SECONDS"
          
          SECONDS=0
          
          echo "$SECONDS"
          sleep 10
          echo "$SECONDS"


          start_time=$(date +%s%N)
          sleep 1
          end_time=$(date +%s%N)
          elapsed=$(( (end_time - start_time) / 1000000 ))
          echo "Elapsed ${elapsed}ms"
