name: Test workflow call

on:
  workflow_call:
    inputs:
      cluster:
        type: string
        required: true

jobs:
  do_work_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting"
      - run: sleep 10
      - run: echo "Done"
  do_work_2:
    runs-on: ubuntu-latest
    needs: do_work_1
    steps:
      - run: echo "Starting"
      - run: sleep 2
      - run: echo "Done"
  do_work_3:
    runs-on: ubuntu-latest
    needs: do_work_1
    steps:
      - run: echo "Starting"
      - run: sleep 3
      - run: echo "Done"
